import 'package:flutter/material.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_homedarkwidget/generated/GeneratedServicesWidget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_homedarkwidget/generated/GeneratedVectorWidget17.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_homedarkwidget/generated/GeneratedGroup69Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_homedarkwidget/generated/GeneratedGroup75Widget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_homedarkwidget/generated/GeneratedGroup71Widget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_homedarkwidget/generated/GeneratedGroup25Widget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_homedarkwidget/generated/GeneratedGroup23Widget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_homedarkwidget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_homedarkwidget/generated/GeneratedGroup26Widget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_homedarkwidget/generated/GeneratedGroup68Widget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_homedarkwidget/generated/GeneratedAccountOverviewWidget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_homedarkwidget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_homedarkwidget/generated/GeneratedSendMoneyWidget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_homedarkwidget/generated/GeneratedGroup27Widget.dart';

/* Frame eWalle_home.dark
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEWalle_homedarkWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 23, 24, 34),
                ),
              ),
              Positioned(
                left: 25.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 325.0001220703125,
                height: 32.0,
                child: GeneratedGroup19Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.37066666666666664;

                  final double height =
                      constraints.maxHeight * 0.0332512315270936;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06666666666666667,
                        y: constraints.maxHeight * 0.13793103448275862,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAccountOverviewWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.256;

                  final double height =
                      constraints.maxHeight * 0.0332512315270936;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06666666666666667,
                        y: constraints.maxHeight * 0.3854679802955665,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSendMoneyWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.176;

                  final double height =
                      constraints.maxHeight * 0.03694581280788178;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06666666666666667,
                        y: constraints.maxHeight * 0.6379310344827587,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedServicesWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 25.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 116.0,
                child: GeneratedGroup22Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 52.0,
                child: GeneratedGroup23Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 96.0,
                child: GeneratedGroup68Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 679.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 96.0,
                child: GeneratedGroup69Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.055301839192708334;

                  final double height =
                      constraints.maxHeight * 0.027093593710161783;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.11733333333333333,
                        y: constraints.maxHeight * 0.7155172413793104,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup71Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.064;
                  double scaleX = (constraints.maxWidth * percentWidth) / 24.0;

                  double percentHeight = 0.019445164450283707;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      15.789473533630371;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8666666666666667,
                        translateY: constraints.maxHeight * 0.6440886699507389,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget17())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.064;

                  final double height =
                      constraints.maxHeight * 0.029556650246305417;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8666666666666667,
                        y: constraints.maxHeight * 0.3854679802955665,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup75Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 97.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 120.0,
                child: GeneratedGroup25Widget(),
              ),
              Positioned(
                left: 207.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 120.0,
                child: GeneratedGroup26Widget(),
              ),
              Positioned(
                left: 317.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 120.0,
                child: GeneratedGroup27Widget(),
              )
            ]),
      ),
    ));
  }
}
