import 'package:flutter/material.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_design_lightwidget/generated/GeneratedGroup123Widget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_design_lightwidget/generated/GeneratedGroup124Widget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_design_lightwidget/generated/GeneratedC2Widget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_design_lightwidget/generated/GeneratedGroup128Widget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_design_lightwidget/generated/GeneratedC1Widget.dart';

/* Frame eWalle_Design_Light
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEWalle_Design_LightWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1325.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1600.0,
                      height: 1200.0,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.0, 1.0],
                          colors: [
                            Color.fromARGB(255, 226, 231, 240),
                            Color.fromARGB(255, 241, 243, 246)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: -110.0,
                              top: 879.0,
                              right: null,
                              bottom: null,
                              width: 446.0,
                              height: 446.0,
                              child: GeneratedC1Widget(),
                            ),
                            Positioned(
                              left: 893.0,
                              top: -98.0,
                              right: null,
                              bottom: null,
                              width: 1110.0,
                              height: 1110.0,
                              child: GeneratedC2Widget(),
                            ),
                            Positioned(
                              left: 1405.0,
                              top: 1102.0,
                              right: null,
                              bottom: null,
                              width: 135.0,
                              height: 50.0,
                              child: GeneratedGroup123Widget(),
                            ),
                            Positioned(
                              left: 729.0,
                              top: 1112.0,
                              right: null,
                              bottom: null,
                              width: 141.0,
                              height: 31.0,
                              child: GeneratedGroup124Widget(),
                            ),
                            Positioned(
                              left: 126.0,
                              top: 150.0,
                              right: null,
                              bottom: null,
                              width: 1347.640380859375,
                              height: 900.0,
                              child: GeneratedGroup128Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
