import 'package:flutter/material.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_logindarkwidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/nkeloapp/generatedewalle_logindarkwidget/generated/GeneratedGroup127Widget.dart';

/* Frame eWalle_login.dark
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEWalle_logindarkWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 23, 24, 34),
                ),
              ),
              Positioned(
                left: -68.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 268.33331298828125,
                height: 812.0,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: 159.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 729.0,
                child: GeneratedGroup127Widget(),
              )
            ]),
      ),
    ));
  }
}
